---
apiVersion: v1
kind: Secret
metadata:
  name: "django-db"
stringData:
  database-name: "django"
  database-password: "not-so-secure-password"
  database-user: "django"
  database-host: "postgres"
  database-port: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: "django"
stringData:
  secret: "not-so-secret-in-here-but-enough-during-development"

---
apiVersion: v1
kind: Service
metadata:
  name: "django"
spec:
  ports:
    - name: tcp-8000
      nodePort: 0
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    name: "django"
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "django"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "django"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: "django"
    spec:
      containers:
        - image: django-app
          name: django
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: "django-db"

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: "django-db"

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: "django-db"

            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  key: database-host
                  name: "django-db"

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  key: database-port
                  name: "django-db"

            - name: DEBUG
              value: "true"

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: "django"

          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
status: {}
